---
- name: When Testing
  hosts: local
  vars:
    my_str: whatever
    version: 'Cisco IOS running  version 15.3'
  tasks:
    - name: Hardcoded to False
      debug:
        msg: Hello World is False
      when: False

    - name: Hardcoded to True
      debug:
        msg: Hello World is True
      when: True

    - name: Testing String equality
      debug:
        msg: whatever
      when: my_str == 'whatever'

    - name: Testing String equality
      debug:
        msg: This is Cisco IOS
      when: "'Cisco IOS' in version"

    - name: This variable is defined
      debug:
        msg: Variable Defined
      when: version is defined

    - command: /bin/False
      register: result
      ignore_errors: True

    - debug:
        msg: "Hello World"
      when: result|failed
